# Generated by Django 5.2.7 on 2025-11-25 09:43

from django.conf import settings
from django.db import migrations, models


def seed_positions(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')
    owner_ids = Task.objects.values_list('owner_id', flat=True).distinct()
    for owner_id in owner_ids:
        tasks = list(Task.objects.filter(owner_id=owner_id).order_by('-created_at', '-id'))
        total = len(tasks)
        for index, task in enumerate(tasks):
            task.position = total - index
            task.save(update_fields=['position'])


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-position', '-created_at']},
        ),
        migrations.AddField(
            model_name='task',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['-position'], name='tasks_task_positio_83eca2_idx'),
        ),
        migrations.RunPython(seed_positions, migrations.RunPython.noop),
    ]
